### ISSUE TITLE
You will make meaningful use of REST APIs (You may use Python’s request library, as well as OAuth2.)

### ISSUE THREAD

**Issue by tofr** [JoanChirinos/LetNogo#2]

**Comment by JoanChirinos** [comment]
>* Some teams have keys.json files with multiple keys.
>* Some teams seem to be scrambling now to retroactively bolt-on some REST API functionality. (If this is you, don't tear it all down and start from scratch; it is too late for that. Do what you can.)
>* Some teams are using APIs requiring keys but have not set up their keys dir
>* Some teams are using key-less APIs, but their README makes no mention of them...

I don't believe the first 3 bullets apply to our team. [This](https://github.com/JoanChirinos/LetNogo#api-information) link leads to the section in the README where we state that our APIs are keyless. Could there be some other reason you've created this issue?

**Comment by tofr** [comment]
Looks like you're clear.


Topher Mykolyk
Stuyvesant CS
+
